redscientistlabs/RTCV

.editorconfig
Source/Frontend/UI/Components/Blast Editor/RTC_SanitizeTool_Form.cs
Source/Frontend/UI/Components/Glitch Harvester/RTC_SavestateManager_Form.cs
Source/Frontend/UI/Forms/RTC_AnalyticsTool_Form.cs
Source/Frontend/UI/Input/Bindings.cs
Source/Frontend/UI/Input/Input.cs
Source/Frontend/UI/UIConnector.cs
Source/Frontend/UI/UICore.cs
Source/Frontend/UI/UI_Extensions.cs
Source/Libraries/Common/StaticTools.cs
Source/Libraries/CorruptCore/CorruptCoreConnector.cs
Source/Libraries/CorruptCore/CorruptCore_Extensions.cs
Source/Libraries/CorruptCore/Diff.cs
Source/Libraries/CorruptCore/Filtering.cs
Source/Libraries/CorruptCore/Objects.cs
Source/Libraries/CorruptCore/StepActions.cs
Source/Libraries/NetCore/NetCore_Extensions.cs

Fixed the following rules:
- CA1823 - Unused field
- CA1715 - Prefix generic type parameter name with 'T'
- SA1003 - Operator whitespace
- SA1120 - Comments should contain text
- SA1132 - Do not combine fields

Fixing FxCop and StyleCop rules

---

.editorconfig
Source/Libraries/PluginHost/Host.cs

Only one instance. Unfortunately, the compiler isn't smart enough to realize that MEF will handle the assignment of that variable.

"Fixed" CS0649 - Field never assigned to

---

.github/workflows/buildConsumers.yml

My goal with this change is to avoid having check-ins to RTCV break Bizhawk-Vanguard or CemuStub-Vanguard.
To accomplish this, PRs and pushes to the `505` branch will checkout and build Bizhawk-Vanguard and CemuStub-Vanguard on their master branches.
This change will potentially break RTCV's CI if:
- Breaking changes are checked-in to RTCV that don't have corresponding fixes in Bizhawk/CemuStub
- Breaking changes are checked-in to Bizhawk/CemuStub that don't have a corresponding fix in RTCV.
This change may not be the best way to accomplish my goal, but it may be an improvement over nothing.
[Passing build example here](https://github.com/scowalt/RTCV/runs/770728516?check_suite_focus=true)

Build Bizhawk and CemuStub in RTCV 505 branch

---

.editorconfig
Source/Frontend/UI/UI_Extensions.cs
Source/Libraries/Common/StaticTools.cs

`IColorable` is dead code.
`IAutoColorize` is used in many places in the code. I added this empty interface as an exception.

Fixed CA1040 - Avoid empty interfaces

---

.editorconfig
Source/Frontend/UI/Input/Input.cs
Source/Libraries/CorruptCore/MemoryDomains.cs

For `CA1065`, I'm not touching the only current violation, but I think it's worthwhile to prevent further violations.
For `CA1066`, I fixed the only violation, implementing the `IEquatable` interface.

Fixed CA1065 and CA1066

---

.editorconfig
Source/Frontend/UI/Components/Memory Tools/RTC_VmdAct_Form.cs

[This article](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca5369?view=vs-2019) has a pretty concise breakdown of the motivation behind this fix.
I doubt this has any functional impact on the code, but I also haven't tested it. If you give me a scenario that hits `RTC_VmdAct_Form::btnActiveTableAddFile_Click` I can run it locally to make sure there are no functional issues.

Fixed CA3075 and CA5369 - Unsafe Deserialize

---

.editorconfig
Source/Frontend/StandaloneRTC/Properties/AssemblyInfo.cs
Source/Frontend/UI/Properties/AssemblyInfo.cs

`NeutralResourcesLanguage` attributes were required to be added to a couple of the projects.
I missed these warnings in my initial fix because VSCode swallows project-level warnings (warnings that don't originate from source code).

Fixed CA1824 (for real this time) - NeutralResourcesLanguage

---

Source/Frontend/UI/Components/Memory Tools/RTC_VmdGen_Form.cs
Source/Frontend/UI/Components/Memory Tools/RTC_VmdSimpleGen_Form.cs
Source/Libraries/CorruptCore/MemoryDomains.cs

Multiple different VMD generation forms had identical logic to parse a line and add it to a `VmdPrototype`. I refactored this out into one single function.

Remove duplicate code in VMD generation

---

Source/Libraries/NetCore/NetCoreObjects.cs

Lots of duplicate code here to acquire the mutex before running a function. I created a helper function to acquire the mutex to remove this duplicate code.

Remove duplicate code in `NetCoreSpec`

---

Source/Libraries/CorruptCore/CorruptCore.cs
Source/Libraries/CorruptCore/CorruptCoreConnector.cs

A couple of spots in code handle generating multiple `BlastLayer`s based on the number of threads. This change refactors those two spots to use the same help function. I cleaned up the code in this help function a bit to match our `.editorconfig` standards.

Refactor duplicate `GenerateBlastLayer` code

---

Source/Frontend/UI/Components/Memory Tools/Common.cs
Source/Frontend/UI/Components/Memory Tools/RTC_MyLists.cs
Source/Frontend/UI/Components/Memory Tools/RTC_MyVMDs_Form.cs
Source/Frontend/UI/UI.csproj

Both `RTC_MyVMDs_Form` and `RTC_MyLists_Form` have identical code to copy a file with a blocking overwrite confirmation dialog. This change refactors that to call into a shared helper function.

[Refactor] Merge duplicate file copy code in Memory Tools

---

Source/Frontend/UI/Components/Memory Tools/RTC_VmdAct_Form.cs
Source/Libraries/CorruptCore/ActivationTableObject.cs
Source/Libraries/CorruptCore/CorruptCore.csproj

In #53, I ended up breaking `RTC_VmdAct_Form` by changing the scope and namespace of `ActiveTableObject`.
I'm not entirely sure why that happened, but this is a quick fix.
I've validated locally that the Standalone RTC will launch with this change.

[Bugfix] Fix crash on launch for Standalone RTC

---

.editorconfig
Source/Frontend/UI/Input/Keyboard.cs
Source/Libraries/CorruptCore/Diff.cs

Per [the documentation for CA1815](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1815?view=vs-2019), violations can be safely ignored if the struct is never used for comparison. In this case, neither violating struct is used in a comparison. I disabled the warning for each of the non-violations.

Fixed CA1815 - Structs should override comparison operators

---

.editorconfig
Source/Frontend/UI/AutoKillSwitch.cs
Source/Frontend/UI/Components/Blast Editor/RTC_SanitizeTool_Form.cs
Source/Frontend/UI/Components/Glitch Harvester/RTC_StockpileManager_Form.cs
Source/Frontend/UI/Forms/RTC_AnalyticsTool_Form.cs
Source/Frontend/UI/Input/Gamepad.cs
Source/Frontend/UI/Modular/UI_CanvasForm.cs
Source/Libraries/Common/Controls/LogConsole.cs
Source/Libraries/Common/Forms/LogConsoleForm.cs
Source/Libraries/CorruptCore/Blast Generator Engines/RTC_StoreGenerator.cs
Source/Libraries/CorruptCore/BlastGeneratorProto.cs
Source/Libraries/CorruptCore/BlastTools.cs
Source/Libraries/CorruptCore/BlastUnit.cs
Source/Libraries/CorruptCore/CorruptCoreConnector.cs
Source/Libraries/CorruptCore/Corruption Engines/RTC_ClusterEngine.cs
Source/Libraries/CorruptCore/Corruption Engines/RTC_VectorEngine.cs
Source/Libraries/CorruptCore/Filtering.cs
Source/Libraries/CorruptCore/MemoryDomains.cs
Source/Libraries/CorruptCore/StockpileManager_EmuSide.cs
Source/Libraries/CorruptCore/StockpileManager_UISide.cs
Source/Libraries/NetCore/DebugInfo/CloudDebug_Form.cs
Source/Libraries/NetCore/SyncObjectSingleton.cs
Source/Libraries/PluginHost/Host.cs

This change fixes `CA1801`.
There were lots of functions in the code that had parameters that weren't used in the function body. I fixed all of those instances.

[Cleanup] Remove unused parameters from functions

---

.editorconfig
Source/Libraries/NetCore/Connector.cs
Source/Libraries/NetCore/UDPLink.cs

Per the [documentation for CA2200](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2200?view=vs-2019), rethrown exceptions should be thrown implicitly to avoid overriding stack information.
This change fixes all violations of CA2200.

Fix CA2200 - Rethrow to preserve stack details

---

Source/Frontend/UI/UI_Extensions.cs
Source/Libraries/Common/Common.csproj
Source/Libraries/Common/Extensions/TExtensions.cs
Source/Libraries/CorruptCore/CorruptCore_Extensions.cs

Both `UI` and `CorruptCore` had a `Clamp<T>` implementation. I moved this implementation to the `Common` library.
This change may break dependants if they are using this helper function.

[Refactor] Merge duplicate Clamp<T> implementations

---

Source/Frontend/UI/Components/Controls/InputCompositeWidget.cs
Source/Frontend/UI/Input/Input.cs
Source/Frontend/UI/Input/LogicalButton.cs
Source/Frontend/UI/Input/ModifierKeys.cs
Source/Frontend/UI/UI.csproj

`RTCV.UI.Input.Input` is a class which has some types/classes defined inside of it. This generally isn't in good form, and violates [CA1034](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1034?view=vs-2019).
This change moves some types/classes defined inside of `RTCV.UI.Input.Input` to their own files.
This change will likely break dependants, so I'm listing this as a draft until we have a stronger CI validation pipeline.

[Refactor] Input class breakup

---

Source/Frontend/UI/Components/Controls/HexTextBox.cs

`_maxSize` never has a value set. I feel like this may be a bug.

[Cleanup] HexTextBox._maxSize cleanup

---

Source/Frontend/UI/Input/Input.cs
Source/Frontend/UI/Input/InputEvent.cs
Source/Frontend/UI/UI.csproj
Source/Frontend/UI/UICore.cs

Per CA1034, type definitions shouldn't be nested. `InputEvent` and `InputEventType` have definitions nested inside of the `Input` class.

[Refactor] Move InputEvent to its own file

---

Source/Libraries/CorruptCore/CorruptCoreConnector.cs

`OnMessageReceived` is a massive message handling function. I've broken up most of the individual actions taken by each of the switches with helper functions.

[Refactor] Breakup CorruptCoreConnector.OnMessageReceived into helper functions

---

Source/Libraries/CorruptCore/BlastUnit.cs
Source/Libraries/CorruptCore/BlastUnitWorkingData.cs
Source/Libraries/CorruptCore/CorruptCore.csproj

Continuing to conform to the guideline of "one class definition per file".
Eventually, it would be nice to move all of the `Blast*.cs` files to their own folder and all of the `Blast*` classes to their own namespace. Changing CorruptCore in any substantial way, however, would likely have butterfly effects on the emulators.

[Refactor] BlastUnitWorkingData is now its own file

---

Source/Libraries/CorruptCore/Diff.cs

- `Item` being defined inside of `Diff` was a violation of `CA1034`
- `Diff` could be made a static class

[Cleanup] Minor `Diff` fixes

---

Source/Frontend/UI/Input/IPCKeyInput.cs
Source/Frontend/UI/Input/Keyboard.cs

Per `CA1034`, avoid using nested types.

[Refactor] Unnest KeyEvent definition

---

.github/dependabot.yml

Check out the pull requests on my fork for an example of what this looks like https://github.com/scowalt/RTCV/pulls
Curious if this type of automated dependency tracking is something we want to implement

Add DependaBot to repository

---

.github/workflows/build.yml

Since the launch is in its own repository, we'll no longer build it from here.

[Cleanup] Remove Launcher from CI

---

.editorconfig
Source/Libraries/CorruptCore/IRealTime.cs
Source/Libraries/PluginHost/Host.cs
Source/Libraries/PluginHost/IPlugin.cs
Source/Plugins/HexEditor/Loader.cs
Source/Plugins/ScriptHost/Loader.cs
Source/Plugins/TestPlugin/TestPlugin.cs

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1716?view=vs-2019
This is a particularly nice rule since we're integrating our code into C++ codebases

Fixed CA1716 - Identifiers should not match keywords

---

.editorconfig
Source/Frontend/UI/Input/Gamepad360.cs
Source/Frontend/UI/Input/Input.cs
Source/Libraries/CorruptCore/CorruptCoreExtensions.cs
Source/Libraries/CorruptCore/LogConsole.cs

`Win32` was fixed with a renamed. `Input` was fixed by making the class internal. I also deleted a bunch of dead code.

Fixed CA1724: Type names should not match namespaces

---

Source/Libraries/CorruptCore/Stockpile/Stockpile.cs
Tests/CorruptCore/Serialization/Resources/DefaultStockpile505.json
Tests/CorruptCore/Serialization/StockpileTests.cs

Resolves #241 
Removed `Stockpile.Name`. This has an impact on how `Stockpile` serializes. I created `TestDefaultStockpile505Deserialization` to validate that `Stockpile`s created before this commit can still successfully be deserialized

Removed Stockpile.Name member

---

.github/workflows/build.yml
.github/workflows/buildDependants.yml

On October 1, [GitHub deprecated commands used by `setup-msbuild`](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) to set the `PATH` environment variable. As a result, all of our CI is currently broken at the `setup-msbuild` step.
As a workaround, I've updated all of the tasks that use `setup-msbuild` to include the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable, which will override the command deprecation.
At some point, this same fix will need to be applied to all of the dependant projects for CI to work properly.

[CI] Updated setup-msbuild tasks

---

.github/workflows/buildDependants.yml
Development/Projects.json
Development/Run.ps1
README.md

Per discord discussions, UnityStub is deprecated. This PR removes UnityStub from the build scripts and CI to avoid build error noise.

Remove UnityStub support

---

nuget.config

Bug: https://github.com/NuGet/Home/issues/10586
Workaround: Add a `nuget.config` file to explicitly clear local package sources and add the nuget repo. I don't fully understand the ramifications of this; there might be a perf hit locally or in the CI system or both.

[CI] Nuget Restore fix

---

Source/Frontend/UI/Components/Glitch Harvester/StockpileManagerForm.cs

Shift+Select was taking the last savestate from the selection, instead of the first. Historically, RTC has always taken the first savestate in this context. This change brings consistency back between how shift/ctrl work when multi-selecting.

Fix Incorrect Merge Behavior

---

Source/Frontend/UI/Components/Engine Config/MemoryDomainsForm.cs

Option to regenerate profiled VMDs no longer always greyed out when such VMDs exist

Fix 'Regenerate Profiled VMDs'

---

Source/Frontend/UI/Components/Controls/SavestateList.cs
Source/Frontend/UI/Components/Engine Config/MemoryDomainsForm.cs

Fix 'index out of range' when attempting to delete a state when the statelist is already empty.

Fix 'Index Out Of Range' in SavestateList

---

Source/Libraries/CorruptCore/BlastUnit.cs

Units of 16bits+ receive randomized values instead of all 00s (depending on settings; origin mode/lists are respected, except for unsupported bitlogiclists)

Fix Reroll for Units Above 8bit Precision

---

Source/Frontend/UI/Forms/BlastEditorForm.cs
Source/Libraries/CorruptCore/BlastUnit.cs

Blast Editor 'Bake All Blastunits to VALUE' now processes entire blastlayer instead of just the first unit. Individual selections still work as expected.

Fix 'Bake All Blastunits to VALUE'

---

Source/Libraries/PluginHost/Host.cs
Source/Libraries/Vanguard/VanguardConnector.cs

Fixed a crash loop that occurred when a plugin implementing a new ListFilter class was unable to be deserialized on the emulator side after reconnecting to NetCore

Fixed ListFilter Plugin Crash Loop

---

Source/Frontend/UI/VanguardImplementation.cs

This is so filestub templates can make vmds out of certain files.

VanguardImplementation: Allow the Emu Side to make VMDs

---

Source/Frontend/UI/Components/Engine Config/CorruptionEngineForm.cs

Fixed plugin engine controls not hiding on deselection.
Also fixed `previousPluginEngine` variable being set to the new plugin engine.

Fixed plugin engine controls not hiding on deselection
