- .editorconfig
- .github/workflows/build.yml
- .gitignore
- Directory.Build.props
- Source/Frontend/UI/Components/Controls/InputCompositeWidget.cs
- Source/Frontend/UI/UI_Extensions.cs
- Source/Libraries/Common/Logging.cs
- Source/Libraries/CorruptCore/MemoryDomains.cs
- Fixed `CA1802`, removed dead code
- Updated `StyleCop.Analyzers` to the latest version
- Updated build script dependencies
> Fix CA1802 + dependency updates

- .editorconfig
- Source/Libraries/CorruptCore/Blast Generator Engines/RTC_StoreGenerator.cs
`RTC_StoreGenerator` is now a `static` class
> Fixed CA1052 - Type is a static holder type but is neither static nor NotInheritable

- .editorconfig
- Source/Frontend/UI/Components/Controls/InputCompositeWidget.cs
- Source/Frontend/UI/Forms/RTC_BlastGenerator_Form.cs
- Source/Frontend/UI/Input/Input.cs
- Source/Libraries/CorruptCore/Blast Generator Engines/RTC_StoreGenerator.cs
- Source/Libraries/CorruptCore/Blast Generator Engines/RTC_ValueGenerator.cs
- Source/Libraries/CorruptCore/Enums.cs
- Source/Libraries/CorruptCore/Objects.cs
> Fixed enum naming (plurality)

- .editorconfig
- Source/Frontend/UI/UI_Extensions.cs
- Source/Libraries/CorruptCore/CorruptCore_Extensions.cs
> Fix invalid use of ArgumentOutOfRangeException

- .editorconfig
- Source/Frontend/UI/Components/Blast Editor/RTC_ColumnSelector_Form.cs
- Source/Frontend/UI/Components/Blast Editor/RTC_SanitizeTool_Form.cs
- Source/Libraries/CorruptCore/CorruptCore.cs
- Source/Libraries/CorruptCore/MemoryDomains.cs
- Source/Plugins/HexEditor/HexEditor.cs
- Fixes `CA1827`
- Fixes `CA1829`
> Fix improper use of Count

- .editorconfig
> Fixed CA1824

- .editorconfig
- Source/Frontend/UI/Components/Blast Editor/RTC_ColumnSelector_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_ListGen_Form.cs
- Source/Frontend/UI/Forms/RTC_AnalyticsTool_Form.cs
- Source/Frontend/UI/Forms/RTC_BlastGenerator_Form.cs
- Source/Frontend/UI/Forms/RTC_NewBlastEditor_Form.cs
- Source/Frontend/UI/UI_Extensions.cs
- Source/Libraries/CorruptCore/CorruptCore_Extensions.cs
- Source/Libraries/CorruptCore/Filtering.cs
- Source/Libraries/CorruptCore/ListFilters.cs
- Source/Libraries/CorruptCore/Objects.cs
- Source/Libraries/NetCore/NetCore_Extensions.cs
- Source/Libraries/NetCore/ReturnWatch.cs
- Source/Libraries/NetCore/TCPLink.cs
More info here: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1121.md
> Fixed SA1121 - Use type aliases

- .editorconfig
- Source/Frontend/UI/Components/Blast Editor/RTC_SanitizeTool_Form.cs
- Source/Frontend/UI/Components/Glitch Harvester/RTC_GlitchHarvesterBlast_Form.cs
- Source/Frontend/UI/Components/Glitch Harvester/RTC_SavestateManager_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_MyLists.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_MyVMDs_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_VmdAct_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_VmdPool_Form.cs
- Source/Frontend/UI/Forms/RTC_AnalyticsTool_Form.cs
- Source/Frontend/UI/Forms/RTC_Intro_Form.cs
- Source/Frontend/UI/Forms/RTC_NewBlastEditor_Form.cs
- Source/Frontend/UI/Forms/RTC_StockpilePlayer_Form.cs
- Source/Frontend/UI/Modular/UI_CoreForm.cs
- Source/Frontend/UI/UI_VanguardImplementation.cs
- Source/Libraries/CorruptCore/Blast Generator Engines/RTC_StoreGenerator.cs
- Source/Libraries/CorruptCore/Blast Generator Engines/RTC_ValueGenerator.cs
- Source/Libraries/CorruptCore/CorruptCore.cs
- Source/Libraries/CorruptCore/CorruptCoreConnector.cs
- Source/Libraries/CorruptCore/Objects.cs
- Source/Libraries/CorruptCore/StepActions.cs
- Source/Libraries/NetCore/DebugInfo/CloudDebug_Form.cs
- Source/Libraries/NetCore/LocalRouter.cs
- Source/Libraries/NetCore/ReturnWatch.cs
Fix `CA1032` and `CA2237` by removing `CustomException` and fixing `AbortEverythingException`
> Remove CustomException, fix rules

- README.md
I missed one dependency that's required to build this project without Visual Studio.
> README update to add choco dependency

- .editorconfig
- Source/Frontend/UI/Components/Controls/MultiTrackBar.cs
- Source/Frontend/UI/Components/Engine Config/RTC_MemoryDomains_Form.cs
- Source/Frontend/UI/Components/Glitch Harvester/RTC_SavestateManager_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_DomainAnalytics_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_VmdAct_Form.cs
- Source/Frontend/UI/Forms/RTC_BlastGenerator_Form.cs
- Source/Frontend/UI/Forms/RTC_NewBlastEditor_Form.cs
- Source/Frontend/UI/Forms/RTC_Settings_Form.cs
- Source/Frontend/UI/Modular/UI_CanvasForm.cs
- Source/Frontend/UI/Modular/UI_ComponentFormTile.cs
- Source/Frontend/UI/Modular/UI_CoreForm.cs
- Source/Frontend/UI/Modular/UI_ShadowPanel.cs
- Source/Frontend/UI/UIConnector.cs
- Source/Libraries/Common/StaticTools.cs
- Source/Libraries/NetCore/Connector.cs
- Source/Libraries/NetCore/MessageHub.cs
- Source/Libraries/NetCore/NetCoreObjects.cs
- Source/Libraries/NetCore/NetCore_Extensions.cs
- Source/Libraries/NetCore/ReturnWatch.cs
- Source/Libraries/NetCore/TCPLink.cs
- Source/Libraries/NetCore/TCPLinkWatch.cs
- Source/Libraries/NetCore/UDPLink.cs
- Source/Libraries/PluginHost/Host.cs
- Source/Libraries/Vanguard/VanguardConnector.cs
- Source/Plugins/HexEditor/HexEditor.cs
Reverts ircluzar/RTCV#12
After discussion with @ircluzar  we determined that, although it's just IDisposable, we shouldn't be adding stuff shortly before an RC (we want to release a stable build very soon). 
There's a new 506 branch, please rebase any PRs there @scowalt
> Revert "Fix Disposable classes"

- Source/Libraries/NetCore/TCPLink.cs
`StoreMessages` is a relatively complex function. I refactored out a couple of pieces to helper functions, and I did some polishing on the rest of the file.
> Minor TCPLink refactor

- .editorconfig
Fixed "for free" by some of my other work. Just enabling this rule.
> [Style] Fixed SA1141

- .editorconfig
- Source/Frontend/UI/Forms/RTC_NewBlastEditor_Form.cs
Lots of very minor changes here. I definitely want to see if I can refactor this file more in a future change. For now, I'm just tidying up.
> [Cleanup] NewBlastEditor cleanup

- Source/Frontend/UI/Extensions/NumberExtensions.cs
- Source/Frontend/UI/UI.csproj
- Source/Frontend/UI/UI_Extensions.cs
Per #65, moving code out of `UI_Extensions.cs`
> [Refactor] Move UI.NumberExtensions

- Source/Plugins/HexEditor/HexEditor.Designer.cs
- Source/Plugins/HexEditor/HexEditor.cs
- Source/Plugins/HexEditor/HexTextBox.cs
- Source/Plugins/HexEditor/Loader.cs
- Source/Plugins/HexEditor/VanguardConnector.cs
Cleaned up almost all of the IDE info issues in the `HexEditor` project.
> [Cleanup] HexEditor IDE info fixes

- Source/Frontend/UI/Components/Controls/SavestateList.cs
- Source/Frontend/UI/Forms/RTC_SimpleMode_Form.cs
Fixed all `IDExxxx` issues in this file.
> [Cleanup] Fix SavestateList IDE issues

- Source/Frontend/UI/UI_VanguardImplementation.cs
This is a similar change to #76, but much more thorough
This is an important first step towards whatever more wholistic refactor/rethink we want to do later.
> [Refactor] UI_VanguardImplementation.OnMessageReceived now uses helper functions

- Source/Libraries/CorruptCore/CorruptCore_Extensions.cs
- Source/Libraries/CorruptCore/Corruption Engines/RTC_CustomEngine.cs
- Source/Libraries/NetCore/NetCore.csproj
- Source/Libraries/NetCore/NetCore_Extensions.cs
- Source/Libraries/NetCore/SafeJsonTypeSerialization/JsonKnownTypesBinder.cs
- Source/Libraries/NetCore/SafeJsonTypeSerialization/TypeWrapper.cs
- Source/Libraries/NetCore/SafeJsonTypeSerialization/UntypedToTypedValueContractResolver.cs
- Source/Libraries/NetCore/SafeJsonTypeSerialization/UntypedToTypedValueConverter.cs
Helps break up `NetCore_Extensions.cs` and complies with `CA1034`
> [Refactor] Convert SafeJsonTypeSerialization to namespace

- Source/Frontend/UI/Components/NumericTextBox.cs
- Source/Frontend/UI/Forms/RTC_NewBlastEditor_Form.Designer.cs
- Source/Frontend/UI/UI.csproj
- Source/Frontend/UI/UI_Extensions.cs
> [Refactor] Move NumericTextBox to its own file

- .editorconfig
- Source/Frontend/UI/Components/Blast Editor/RTC_SanitizeTool_Form.cs
- Source/Frontend/UI/Components/Controls/InputWidget.cs
- Source/Frontend/UI/Components/DataGridViewNumericUpDownCell.cs
- Source/Frontend/UI/Components/Glitch Harvester/RTC_SavestateManager_Form.cs
- Source/Frontend/UI/Components/Glitch Harvester/RTC_StashHistory_Form.cs
- Source/Frontend/UI/Components/Glitch Harvester/RTC_StockpileManager_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_DomainAnalytics_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_ListGen_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_VmdAct_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_VmdLimiterProfiler_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_VmdPool_Form.cs
- Source/Frontend/UI/Components/Settings/RTC_SettingsNetCore_Form.cs
- Source/Frontend/UI/Forms/RTC_BlastGenerator_Form.cs
- Source/Frontend/UI/Forms/RTC_NewBlastEditor_Form.cs
- Source/Frontend/UI/Forms/RTC_SimpleMode_Form.cs
- Source/Frontend/UI/Input/Input.cs
- Source/Frontend/UI/Modular/UI_CoreForm.cs
- Source/Frontend/UI/UICore.cs
- Source/Libraries/CorruptCore/BitlogicListFilter.cs
- Source/Libraries/CorruptCore/CorruptCoreConnector.cs
- Source/Libraries/CorruptCore/CorruptCore_Extensions.cs
- Source/Libraries/CorruptCore/Memory/VmdPrototype.cs
- Source/Libraries/NetCore/NetCoreObjects.cs
- Source/Libraries/NetCore/TCPLink.cs
- Source/Libraries/Vanguard/VanguardConnector.cs
- Source/Plugins/HexEditor/HexEditor.cs
Lots of methods and classes were able to be made `static`.
> [Cleanup] Fixed CA1822 - Static

- .editorconfig
- Source/Frontend/UI/Input/Gamepad360.cs
- Source/Libraries/NetCore/SafeJsonTypeSerialization/UntypedToTypedValueContractResolver.cs
[CA1810](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1810?view=vs-2019)
> [Cleanup] Fixed CA1810 - Initialize static fields inline

- Source/Frontend/UI/Extensions/BitmapExtensions.cs
- Source/Frontend/UI/UI.csproj
- Source/Frontend/UI/UI_Extensions.cs
> [Refactor] Create BitmapExtensions

- Source/Launcher/Package Downloader/Form1.cs
- Source/Launcher/RTC_Launcher/DownloadForm.cs
- Source/Launcher/RTC_Launcher/LaunchPanelV1.cs
- Source/Launcher/RTC_Launcher/LaunchPanelV2.cs
- Source/Launcher/RTC_Launcher/LaunchPanelV3.cs
- Source/Launcher/RTC_Launcher/MainForm.cs
- Source/Launcher/RTC_Launcher/Objects.cs
- Source/Launcher/RTC_Launcher/Program.cs
- Source/Launcher/RTC_Launcher/Properties/AssemblyInfo.cs
- Source/Launcher/RTC_Launcher/RTC_Extensions.cs
- Source/Launcher/RTC_Launcher/VersionDownloadPanel.cs
Besides the `Uri` changes I made, all of these are non-functional changes to deal with all of the compiler warnings for the Launcher project.
> [Cleanup] Fix all warnings in Launcher project

- Source/Frontend/StandaloneRTC/Loading.cs
- Source/Frontend/UI/Forms/RTC_Standalone_Form.cs
- Source/Frontend/UI/UI.csproj
- Source/Frontend/UI/UICore.cs
- Source/Frontend/UI/UI_Extensions.cs
> [Refactor] Move RTC_Standalone_Form to its own file

- Source/Libraries/NetCore/ConsoleEx.cs
- Source/Libraries/NetCore/NetCore.csproj
- Source/Libraries/NetCore/NetCoreObjects.cs
Breaking up `NetCoreObjects.cs`
> [Refactor] Move ConsoleEx to its own file

- Source/Launcher/RTC_Launcher/MainForm.cs
> [Enhancement] Added confirmation dialog for build deletion

- Source/Launcher/RTC_Launcher/Components/BuildContextMenu.cs
- Source/Launcher/RTC_Launcher/MainForm.cs
- Source/Launcher/RTC_Launcher/RTC_Launcher.csproj
> [Enhancement] Build context menu styling

- .editorconfig
- Source/Frontend/UI/Components/Controls/InputWidget.cs
- Source/Frontend/UI/Components/Controls/MultiTrackBar.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_VmdSimpleGen_Form.cs
- Source/Frontend/UI/Components/Memory Tools/RTC_VmdSimpleGen_Form.designer.cs
- Source/Libraries/CorruptCore/CorruptCore.cs
[CA1034: Nested types should not be visible](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1034?view=vs-2019)
> [Refactor] Fixed all instances of CA1034

- Source/Libraries/CorruptCore/CorruptCore.csproj
- Source/Libraries/CorruptCore/CorruptCore_Extensions.cs
- Source/Libraries/CorruptCore/LogConsole.cs
Trying to clear out `CorruptCore_Extensions.cs`
> [Refactor] Move LogConsole to its own file

- Source/Libraries/NetCore/NetCore_Extensions.cs
- Source/Libraries/NetCore/SyncObjectSingleton.cs
Trying to clear out `NetCore_Extensions.cs`
> [Refactor] Move InvokeCorrectly method

- Source/Frontend/UI/Forms/RTC_NewBlastEditor_Form.cs
- Source/Libraries/CorruptCore/CorruptCore_Extensions.cs
Breaking up `CorruptCore_Extensions.cs`
> [Refactor] Move csv generation code

- .github/workflows/buildDependants.yml
- Development/BuildAll.ps1
This will build all of the projects that have been checked out and setup locally. Any project that isn't found will be skipped.
This should be helpful for local development
> [Dev] Created BuildAll script

- .editorconfig
- Source/Libraries/CorruptCore/CorruptCore.cs
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2234?view=vs-2019
> Fixed CA2234 - Call methods with Uris instead of strings

- .editorconfig
https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1834?view=vs-2019
No remaining violations
> Fixed CA1834 - Use StringBuilder.Append(char) for single character strings

- .editorconfig
- Source/Frontend/UI/Components/Memory Tools/VmdActForm.cs
- Source/Frontend/UI/Components/Memory Tools/VmdGenForm.cs
- Source/Frontend/UI/Components/Memory Tools/VmdLimiterProfilerForm.cs
- Source/Frontend/UI/Components/Memory Tools/VmdSimpleGenForm.cs
- Source/Frontend/UI/Input/Gamepad360.cs
- Source/Libraries/Common/Extensions/RandomExtensions.cs
- Source/Libraries/CorruptCore/CorruptCoreExtensions.cs
- Source/Libraries/CorruptCore/Extensions/ByteArrayExtensions.cs
- Source/Plugins/HexEditor/HexEditor.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1407.md
I think this helps code readability.
> Fixed SA1407 - Arithmetic expression parentheses 

- .editorconfig
- Source/Frontend/UI/Components/DataGridViewNumericUpDownEditingControl.cs
- Source/Libraries/Common/Controls/ToolStripEx.cs
https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1812?view=vs-2019
> Fixed CA1812 - Avoid uninstantiated internal classes

- .editorconfig
- Source/Libraries/Common/Extensions/StringExtensions.cs
- Source/Libraries/CorruptCore/CorruptCoreExtensions.cs
- Source/Libraries/NetCore/NetCoreSpec.cs
- Source/Libraries/NetCore/TCPLink.cs
- Source/Plugins/HexEditor/HexEditor.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1124.md
I'm not willing to die on this hill if we want to leave these regions in.
> Fixed SA1124 - Remove Regions

- Development/BuildAll.ps1
- Development/Modules/Project.psm1
- Development/Modules/RTCVCommand.psm1
- Development/Projects.json
- Development/Run.ps1
- Refactored `BuildAll` to load from `Projects.json`, which should make this a bit easier to expand upon in the future
- Added `Run` command. Example: `.\Development\Run.ps1 -ProjectsToRun Bizhawk,RTCV` will launch Bizhawk and RTCV.
> [Dev] Build script improvements

- Development/Modules/Project.psm1
- Development/Projects.json
- Development/Run.ps1
I also added the ability to run either Debug or Release executables in the `Run.ps1` script.
> Fixed `Run.ps1` script with dolphin and pcsx2

- Source/Frontend/UI/SortableBindingList.cs
- Source/Libraries/CorruptCore/BlastDiff.cs
- Source/Libraries/CorruptCore/Memory/MemoryDomains.cs
- Source/Libraries/CorruptCore/Stockpile/Stockpile.cs
- Source/Libraries/NetCore/LocalRouter.cs
- Source/Libraries/NetCore/MessageHub.cs
- Source/Libraries/NetCore/SafeJsonTypeSerialization/UntypedToTypedValueConverter.cs
See https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching
> Fixed IDE0038 - Use pattern matching

- .editorconfig
- Source/Frontend/UI/Components/DataGridViewNumericUpDownEditingControl.cs
- Source/Frontend/UI/Components/Engine Config/EngineControls/HellgenieEngineControl.cs
- Source/Frontend/UI/Components/Engine Config/EngineControls/NightmareEngineControl.cs
- Source/Frontend/UI/Extensions/ControlExtensions.cs
- Source/Frontend/UI/Forms/BlastEditorForm.cs
- Source/Frontend/UI/Modular/CoreForm.cs
- Source/Libraries/Common/Logging.cs
- Source/Libraries/CorruptCore/BitlogicListFilter.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1203.md
> Fixed SA1203 and other warnings

- Source/Libraries/CorruptCore/StashKey.cs
- Source/Libraries/CorruptCore/Stockpile/Stockpile.cs
- Tests/CorruptCore/Serialization/Resources/DefaultStockpile.json
- Tests/CorruptCore/Serialization/Resources/SimpleStockpile505.json
- Tests/CorruptCore/Serialization/StockpileTests.cs
This fixes some suppression of `CA1051`
> [Refactor] Some Stockpile fields are now properties

- Source/Frontend/UI/Components/Engine Config/CorruptionEngineForm.cs
Added fix for vector unlock always being set to true after checkbox Checked event
> Added fix for vector unlock always being set to true

- Source/Frontend/UI/Components/Engine Config/CorruptionEngineForm.cs
- Source/Frontend/UI/Components/Engine Config/EngineControls/ClusterEngineControl.cs
- Source/Frontend/UI/Components/Engine Config/EngineControls/DistortionEngineControl.Designer.cs
- Source/Frontend/UI/Components/Engine Config/EngineControls/DistortionEngineControl.cs
- Source/Frontend/UI/Components/Engine Config/EngineControls/HellgenieEngineControl.cs
- Source/Frontend/UI/Components/Engine Config/EngineControls/NightmareEngineControl.cs
- Source/Frontend/UI/Components/Engine Config/EngineControls/VectorEngineControl.cs
Also fixed Distortion delay bug
> Implemented engine control resync for most engines
